### ISSUE TITLE
Message: no such element: Unable to locate element issue

### ISSUE THREAD

**Issue by Simsalaba** [yash-dk/stocks-trainer#1]
Hey, great initiative this project. I tried it but I'm getting the following error:

`Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[2]/div[2]/div/div/div[1]/div[1]/div/div/div/div/div[1]/div/div"}
(Session info: chrome=91.0.4472.77)
Report the issue on github.`

**Comment by yash-dk** [comment]
I was not able to replicate it. I guess it's due to not opening the chart in the same tab in which the trainer was opened.
